"""Pure string emit for the EspoCRM adapter (design §10).

Emits each program model as a YAML program file (``ruamel.yaml``, block
style, insertion-ordered keys — *not* ``safe_dump``) and the deferral
set as a ``MANUAL-CONFIG.md`` companion. Both are pure functions of the
model + injected ``rendered_at`` and are byte-stable across runs.
"""

from __future__ import annotations

import io

from ruamel.yaml import YAML

from crmbuilder_v2.adapters.base import Deferral
from crmbuilder_v2.adapters.espocrm.model import EntityProgram, GenerationModel

MANUAL_CONFIG_FILENAME = "MANUAL-CONFIG.md"


def _yaml() -> YAML:
    yaml = YAML()
    yaml.default_flow_style = False
    yaml.width = 4096  # never line-wrap scalars (deterministic, readable)
    yaml.indent(mapping=2, sequence=4, offset=2)
    return yaml


def emit_program_yaml(program: EntityProgram, *, rendered_at: str) -> str:
    """Render one program model to a YAML document string.

    A provenance comment header (carrying ``rendered_at``) precedes the
    document; it is stable for a fixed ``rendered_at`` so two runs match.
    """
    buf = io.StringIO()
    _yaml().dump(program.program, buf)
    body = buf.getvalue()
    header = (
        f"# Generated by the CRMBuilder V2 EspoCRM adapter (PRJ-025 PI-191).\n"
        f"# Source: engine-neutral design records. Rendered at {rendered_at}.\n"
        f"# Do not hand-edit — regenerate from the V2 design model.\n"
    )
    return header + body


def _deferral_table(rows: list[Deferral]) -> list[str]:
    lines = [
        "| Identifier | Name | Parent | Detail |",
        "|---|---|---|---|",
    ]
    for d in rows:
        lines.append(
            f"| {d.identifier} | {d.name} | {d.parent or '—'} | {d.detail} |"
        )
    return lines


def emit_manual_config_md(model: GenerationModel, *, rendered_at: str) -> str:
    """Render the deferral companion. Every deferral the build produced is
    listed (grouped by kind, totally ordered); absence of a group is itself
    stated, so the document never silently drops intent (design §10)."""
    out: list[str] = []
    out.append("# Manual Configuration Required — EspoCRM export")
    out.append("")
    out.append(
        "Engine-neutral design intent that the EspoCRM adapter (PI-191) did "
        "not emit into the deployable YAML, or that the deploy engine treats "
        "as manual configuration. Configure each item via the EspoCRM admin "
        "UI."
    )
    out.append("")
    out.append(
        "**Deploy NOT_SUPPORTED (schema-valid, manual-config at deploy):** the "
        "`savedViews:`, `duplicateChecks:`, and `workflows:` blocks generated "
        "from `view` / `dedup_rule` / `automation` records are emitted into "
        "the program YAML and pass `validate_program()`, but EspoCRM exposes "
        "no public REST write path for them — the Configure run reports each "
        "as `NOT_SUPPORTED` and the operator applies it via the admin UI. The "
        "`emailTemplates:` block (from `message_template` records) is a real "
        "deployable block; its `bodyFile` bodies are written under "
        "`templates/`."
    )
    out.append("")
    out.append(f"- **Engagement:** {model.engagement or '—'}")
    out.append(f"- **Rendered at:** {rendered_at}")
    out.append(f"- **Programs generated:** {len(model.programs)}")
    out.append("")

    # Group deferrals by kind, ordered by kind then (identifier, detail).
    by_kind: dict[str, list[Deferral]] = {}
    for d in model.deferrals:
        by_kind.setdefault(d.kind, []).append(d)

    _titles = {
        "reference_field": "Reference fields (covered by association records)",
        "derived_field": "Derived / formula fields not rendered",
        "unmapped_field": "Unmapped fields",
        "field_attribute": "Field attributes with no deploy-validated YAML key",
        "entity_default_sort": "Entity default-sort intent",
        "association": "Associations not rendered as relationships",
        "field_rule": "Field rules not emitted (valid_when / unrenderable)",
        "entity_rule": "Entity-subject rules",
        "view": "Views not rendered as savedViews",
        "automation": "Automations not rendered as workflows",
        "workflow_action": "Workflow actions not rendered",
        "dedup_rule": "Dedup rules not rendered as duplicateChecks",
        "dedup_normalize": "Dedup normalization tokens not expressible",
        "message_template": "Message templates not rendered as emailTemplates",
        "field_permission": "Field-permission rules not rendered as "
        "fieldPermissions",
        "field_visibility": "Field-visibility rules not rendered as "
        "fieldVisibility",
        "composite_constructs": "Composite constructs (later slices)",
    }
    for kind in sorted(by_kind):
        rows = sorted(by_kind[kind], key=lambda d: (d.identifier, d.detail))
        out.append(f"## {_titles.get(kind, kind)}")
        out.append("")
        out.extend(_deferral_table(rows))
        out.append("")

    return "\n".join(out) + "\n"
