"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-07

Project-management entity schema for the v0.1 storage system per
``storage-system-PRD-v0.1.md`` Section 5. Methodology entities are
deferred to Step 0 follow-on work and add tables in subsequent
migrations without touching this file.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_identifier', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=8), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('before_payload', sa.JSON(), nullable=True),
    sa.Column('after_payload', sa.JSON(), nullable=True),
    sa.CheckConstraint("actor IN ('claude_session', 'manual', 'migration')", name='ck_changelog_actor'),
    sa.CheckConstraint("entity_type IN ('charter', 'decision', 'planning_item', 'reference', 'risk', 'session', 'status', 'topic')", name='ck_changelog_entity_type'),
    sa.CheckConstraint("operation IN ('delete', 'insert', 'update')", name='ck_changelog_operation'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index('ix_changelog_entity', ['entity_type', 'entity_identifier'], unique=False)
        batch_op.create_index('ix_changelog_timestamp', ['timestamp'], unique=False)

    op.create_table('charter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_charter_version')
    )
    with op.batch_alter_table('charter', schema=None) as batch_op:
        batch_op.create_index('ix_charter_is_current', ['is_current'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('decision_date', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('alternatives_considered', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Active', 'Superseded', 'Withdrawn')", name='ck_decision_status'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decisions_identifier', ['identifier'], unique=False)

    op.create_table('planning_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution_reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("item_type IN ('open_question', 'pending_work', 'planning_dimension')", name='ck_planning_type'),
    sa.CheckConstraint("status IN ('Deferred', 'Open', 'Resolved')", name='ck_planning_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relationship_kind IN ('affects', 'blocks', 'covers', 'decided_in', 'is_about', 'references', 'supersedes')", name='ck_ref_relationship'),
    sa.CheckConstraint("source_type IN ('charter', 'decision', 'planning_item', 'risk', 'session', 'status', 'topic')", name='ck_ref_source_type'),
    sa.CheckConstraint("target_type IN ('charter', 'decision', 'planning_item', 'risk', 'session', 'status', 'topic')", name='ck_ref_target_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', 'relationship_kind', name='uq_ref_full')
    )
    with op.batch_alter_table('refs', schema=None) as batch_op:
        batch_op.create_index('ix_refs_source', ['source_type', 'source_id'], unique=False)
        batch_op.create_index('ix_refs_target', ['target_type', 'target_id'], unique=False)

    op.create_table('risks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('probability', sa.String(length=16), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('response_plan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("impact IN ('High', 'Low', 'Medium')", name='ck_risk_impact'),
    sa.CheckConstraint("probability IN ('High', 'Low', 'Medium')", name='ck_risk_probability'),
    sa.CheckConstraint("status IN ('Accepted', 'Closed', 'Mitigated', 'Open')", name='ck_risk_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('session_date', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conversation_reference', sa.Text(), nullable=False),
    sa.Column('topics_covered', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('artifacts_produced', sa.Text(), nullable=False),
    sa.Column('in_flight_at_end', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Complete', 'In Progress')", name='ck_session_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_identifier', ['identifier'], unique=False)
        batch_op.create_index('ix_sessions_session_date', ['session_date'], unique=False)

    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_status_version')
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index('ix_status_is_current', ['is_current'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index('ix_status_is_current')

    op.drop_table('status')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_session_date')
        batch_op.drop_index('ix_sessions_identifier')

    op.drop_table('sessions')
    op.drop_table('risks')
    with op.batch_alter_table('refs', schema=None) as batch_op:
        batch_op.drop_index('ix_refs_target')
        batch_op.drop_index('ix_refs_source')

    op.drop_table('refs')
    op.drop_table('planning_items')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decisions_identifier')

    op.drop_table('decisions')
    with op.batch_alter_table('charter', schema=None) as batch_op:
        batch_op.drop_index('ix_charter_is_current')

    op.drop_table('charter')
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index('ix_changelog_timestamp')
        batch_op.drop_index('ix_changelog_entity')

    op.drop_table('change_log')
    # ### end Alembic commands ###
