"""Deploy wizard — PI-419 (REQ-522, DEC-945).

Five pages that collect everything a deploy run needs and queue it:

1. **Providers** — are the engagement's DigitalOcean and Cloudflare credentials
   in place? (opens :class:`ProviderCredentialsDialog` to set them)
2. **Server** — instance name; region, size, image and account SSH keys from
   the live DigitalOcean catalog.
3. **Domain** — Cloudflare zone, subdomain (with the resulting name shown),
   Let's Encrypt email; explains why the record stays DNS-only.
4. **Accounts** — CRM administrator login (password generated on request);
   database passwords generated by the service unless overridden.
5. **Review** — the request as it will be sent; Deploy queues the run and
   emits :attr:`run_queued` so the caller opens the progress dialog.

Next is never disabled (GVR-217): a page that is not complete explains what is
missing when Next is clicked. All network calls run off the UI thread.
"""

from __future__ import annotations

import logging
import secrets as _random
from typing import Any

from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QDialog,
    QFormLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QStackedWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from crmbuilder_v2.ui.dialogs.error import ErrorDialog
from crmbuilder_v2.ui.dialogs.provider_credentials_dialog import (
    ProviderCredentialsDialog,
)
from crmbuilder_v2.ui.exceptions import (
    RequestShapeError,
    StorageClientError,
    StorageConnectionError,
)
from crmbuilder_v2.ui.widgets.form_helpers import primary_button, required_label
from crmbuilder_v2.ui.workers import drain_workers, run_in_thread

_log = logging.getLogger("crmbuilder_v2.ui.dialogs.deploy_wizard_dialog")

PAGE_PROVIDERS, PAGE_SERVER, PAGE_DOMAIN, PAGE_ACCOUNTS, PAGE_REVIEW = range(5)
_PAGE_TITLES = ("Providers", "Server", "Domain", "Accounts", "Review")


def generate_password(length: int = 20) -> str:
    """A URL-safe random password an administrator can paste anywhere."""
    return _random.token_urlsafe(length)[:length]


class DeployWizardDialog(QDialog):
    """Collect a provisioning request and queue it as a deploy run."""

    #: Emitted with the new run's identifier after a successful queue.
    run_queued = Signal(str)
    connection_lost = Signal(str)

    def __init__(self, client, parent=None) -> None:
        super().__init__(parent)
        self._client = client
        self._in_flight: list = []
        self._providers: dict[str, dict[str, Any]] = {}
        self._options: dict[str, Any] = {}
        self._zones: list[dict[str, Any]] = []
        self.setWindowTitle("Deploy a new CRM instance")
        self.resize(680, 560)

        layout = QVBoxLayout(self)
        self._title = QLabel("")
        self._title.setObjectName("wizard_title")
        self._title.setStyleSheet("font-weight: 600; font-size: 14px;")
        layout.addWidget(self._title)
        self._pages = QStackedWidget()
        layout.addWidget(self._pages, 1)
        self._notice = QLabel("")
        self._notice.setObjectName("wizard_notice")
        self._notice.setWordWrap(True)
        self._notice.setStyleSheet("color: #b9770e;")
        layout.addWidget(self._notice)
        nav = QHBoxLayout()
        nav.addStretch(1)
        self._back_btn = QPushButton("Back")
        self._back_btn.setObjectName("wizard_back")
        self._back_btn.clicked.connect(self._back)
        self._next_btn = primary_button("Next")
        self._next_btn.setObjectName("wizard_next")
        self._next_btn.clicked.connect(self._next)
        cancel_btn = QPushButton("Cancel")
        cancel_btn.setObjectName("wizard_cancel")
        cancel_btn.clicked.connect(self.reject)
        nav.addWidget(cancel_btn)
        nav.addWidget(self._back_btn)
        nav.addWidget(self._next_btn)
        layout.addLayout(nav)

        self._pages.addWidget(self._build_providers_page())
        self._pages.addWidget(self._build_server_page())
        self._pages.addWidget(self._build_domain_page())
        self._pages.addWidget(self._build_accounts_page())
        self._pages.addWidget(self._build_review_page())
        self._show_page(PAGE_PROVIDERS)
        self._load_providers()

    # -- pages -------------------------------------------------------------

    def _build_providers_page(self) -> QWidget:
        page = QWidget()
        v = QVBoxLayout(page)
        intro = QLabel(
            "A deploy run creates a server in DigitalOcean and a DNS record in "
            "Cloudflare using this engagement's provider credentials. Both must "
            "be configured before a run can start."
        )
        intro.setWordWrap(True)
        v.addWidget(intro)
        self._do_status = QLabel("Checking…")
        self._do_status.setObjectName("wizard_do_status")
        self._cf_status = QLabel("Checking…")
        self._cf_status.setObjectName("wizard_cf_status")
        form = QFormLayout()
        form.addRow("DigitalOcean", self._do_status)
        form.addRow("Cloudflare", self._cf_status)
        v.addLayout(form)
        btn = QPushButton("Set credentials…")
        btn.setObjectName("wizard_set_credentials")
        btn.clicked.connect(self._open_credentials)
        v.addWidget(btn, alignment=Qt.AlignmentFlag.AlignLeft)
        v.addStretch(1)
        return page

    def _build_server_page(self) -> QWidget:
        page = QWidget()
        form = QFormLayout(page)
        self.instance_name = QLineEdit()
        self.instance_name.setObjectName("wizard_instance_name")
        self.instance_name.setPlaceholderText("How the instance appears in CRMBuilder")
        form.addRow(required_label("Instance name"), self.instance_name)
        self.region = QComboBox()
        self.region.setObjectName("wizard_region")
        self.region.currentIndexChanged.connect(self._refresh_sizes)
        form.addRow(required_label("Region"), self.region)
        self.size = QComboBox()
        self.size.setObjectName("wizard_size")
        form.addRow(required_label("Size"), self.size)
        self.image = QComboBox()
        self.image.setObjectName("wizard_image")
        form.addRow(required_label("Image"), self.image)
        self.ssh_keys = QListWidget()
        self.ssh_keys.setObjectName("wizard_ssh_keys")
        self.ssh_keys.setMaximumHeight(120)
        form.addRow("Extra SSH keys", self.ssh_keys)
        hint = QLabel(
            "The run generates its own SSH key for the server; tick any account "
            "keys that should also have root access."
        )
        hint.setWordWrap(True)
        hint.setStyleSheet("color: #666;")
        form.addRow("", hint)
        return page

    def _build_domain_page(self) -> QWidget:
        page = QWidget()
        form = QFormLayout(page)
        self.zone = QComboBox()
        self.zone.setObjectName("wizard_zone")
        self.zone.currentIndexChanged.connect(self._refresh_fqdn)
        form.addRow(required_label("Cloudflare zone"), self.zone)
        self.subdomain = QLineEdit()
        self.subdomain.setObjectName("wizard_subdomain")
        self.subdomain.setPlaceholderText("crm")
        self.subdomain.textChanged.connect(self._refresh_fqdn)
        form.addRow(required_label("Subdomain"), self.subdomain)
        self.fqdn = QLabel("—")
        self.fqdn.setObjectName("wizard_fqdn")
        self.fqdn.setStyleSheet("font-weight: 600;")
        form.addRow("Instance address", self.fqdn)
        self.letsencrypt_email = QLineEdit()
        self.letsencrypt_email.setObjectName("wizard_letsencrypt_email")
        self.letsencrypt_email.setPlaceholderText("Receives certificate expiry notices")
        form.addRow(required_label("Let's Encrypt email"), self.letsencrypt_email)
        hint = QLabel(
            "The DNS record is created DNS-only (not proxied through Cloudflare) "
            "so the certificate challenge and SSH reach the server directly. "
            "Leave it that way."
        )
        hint.setWordWrap(True)
        hint.setStyleSheet("color: #666;")
        form.addRow("", hint)
        return page

    def _build_accounts_page(self) -> QWidget:
        page = QWidget()
        form = QFormLayout(page)
        self.admin_username = QLineEdit("admin")
        self.admin_username.setObjectName("wizard_admin_username")
        form.addRow(required_label("Administrator username"), self.admin_username)
        self.admin_email = QLineEdit()
        self.admin_email.setObjectName("wizard_admin_email")
        form.addRow(required_label("Administrator email"), self.admin_email)
        pw_row = QHBoxLayout()
        self.admin_password = QLineEdit()
        self.admin_password.setObjectName("wizard_admin_password")
        self.admin_password.setEchoMode(QLineEdit.EchoMode.Password)
        gen = QPushButton("Generate")
        gen.setObjectName("wizard_generate_password")
        gen.clicked.connect(lambda: self.admin_password.setText(generate_password()))
        show = QCheckBox("Show")
        show.toggled.connect(
            lambda on: self.admin_password.setEchoMode(
                QLineEdit.EchoMode.Normal if on else QLineEdit.EchoMode.Password
            )
        )
        pw_row.addWidget(self.admin_password, 1)
        pw_row.addWidget(gen)
        pw_row.addWidget(show)
        form.addRow(required_label("Administrator password"), pw_row)
        note = QLabel(
            "Record the administrator password now — it is stored encrypted for "
            "the deployment and used as the instance's login for audits and "
            "publishing, but never shown again."
        )
        note.setWordWrap(True)
        note.setStyleSheet("color: #666;")
        form.addRow("", note)
        self.auto_db = QCheckBox("Generate database passwords automatically (recommended)")
        self.auto_db.setObjectName("wizard_auto_db")
        self.auto_db.setChecked(True)
        self.auto_db.toggled.connect(self._toggle_db_fields)
        form.addRow("", self.auto_db)
        self.db_password = QLineEdit()
        self.db_password.setObjectName("wizard_db_password")
        self.db_password.setEchoMode(QLineEdit.EchoMode.Password)
        self.db_root_password = QLineEdit()
        self.db_root_password.setObjectName("wizard_db_root_password")
        self.db_root_password.setEchoMode(QLineEdit.EchoMode.Password)
        form.addRow("Database password", self.db_password)
        form.addRow("Database root password", self.db_root_password)
        self._toggle_db_fields(True)
        return page

    def _build_review_page(self) -> QWidget:
        page = QWidget()
        v = QVBoxLayout(page)
        self.review = QTextEdit()
        self.review.setObjectName("wizard_review")
        self.review.setReadOnly(True)
        v.addWidget(self.review, 1)
        return page

    # -- navigation --------------------------------------------------------

    def _show_page(self, index: int) -> None:
        self._pages.setCurrentIndex(index)
        self._title.setText(f"Step {index + 1} of 5 — {_PAGE_TITLES[index]}")
        self._notice.setText("")
        self._back_btn.setVisible(index > PAGE_PROVIDERS)
        self._next_btn.setText("Deploy" if index == PAGE_REVIEW else "Next")
        if index == PAGE_REVIEW:
            self.review.setPlainText(self.render_review())

    @property
    def page(self) -> int:
        return self._pages.currentIndex()

    def _back(self) -> None:
        if self.page > PAGE_PROVIDERS:
            self._show_page(self.page - 1)

    def _next(self) -> None:
        problem = self.validate_page(self.page)
        if problem:
            self._notice.setText(problem)
            return
        if self.page == PAGE_REVIEW:
            self._deploy()
            return
        self._show_page(self.page + 1)

    def validate_page(self, index: int) -> str | None:
        """Return what is missing on ``index``, or ``None`` when it is complete."""
        if index == PAGE_PROVIDERS:
            missing = [
                name
                for key, name in (("digitalocean", "DigitalOcean"), ("cloudflare", "Cloudflare"))
                if not (self._providers.get(key) or {}).get("configured")
            ]
            if missing:
                return f"Set the {' and '.join(missing)} credential first (Set credentials…)."
        elif index == PAGE_SERVER:
            if not self.instance_name.text().strip():
                return "Give the instance a name."
            if not (self.region.currentData() and self.size.currentData() and self.image.currentData()):
                return "Choose a region, size and image (the DigitalOcean catalog must have loaded)."
        elif index == PAGE_DOMAIN:
            if not self.zone.currentData():
                return "Choose a Cloudflare zone."
            if not self.subdomain.text().strip():
                return "Enter a subdomain."
            if "@" not in self.letsencrypt_email.text():
                return "Enter the Let's Encrypt email."
        elif index == PAGE_ACCOUNTS:
            if not self.admin_username.text().strip():
                return "Enter the administrator username."
            if "@" not in self.admin_email.text():
                return "Enter the administrator email."
            if len(self.admin_password.text()) < 8:
                return "Enter an administrator password of at least 8 characters (or Generate one)."
        return None

    # -- data --------------------------------------------------------------

    def build_body(self) -> dict[str, Any]:
        """The POST /deploy-runs body for the current inputs."""
        body: dict[str, Any] = {
            "instance_name": self.instance_name.text().strip(),
            "region": self.region.currentData(),
            "size": self.size.currentData(),
            "image": self.image.currentData(),
            "ssh_key_ids": [
                self.ssh_keys.item(i).data(Qt.ItemDataRole.UserRole)
                for i in range(self.ssh_keys.count())
                if self.ssh_keys.item(i).checkState() == Qt.CheckState.Checked
            ],
            "zone_id": self.zone.currentData(),
            "zone_name": self.zone.currentText(),
            "subdomain": self.subdomain.text().strip().lower(),
            "letsencrypt_email": self.letsencrypt_email.text().strip(),
            "admin_username": self.admin_username.text().strip(),
            "admin_email": self.admin_email.text().strip(),
            "admin_password": self.admin_password.text(),
        }
        if not self.auto_db.isChecked():
            if self.db_password.text():
                body["db_password"] = self.db_password.text()
            if self.db_root_password.text():
                body["db_root_password"] = self.db_root_password.text()
        return body

    def render_review(self) -> str:
        b = self.build_body()
        keys = ", ".join(str(k) for k in b["ssh_key_ids"]) or "(generated key only)"
        db = "generated by the service" if self.auto_db.isChecked() else "as entered"
        return (
            f"Instance name:      {b['instance_name']}\n"
            f"Address:            https://{b['subdomain']}.{b['zone_name']}\n"
            f"Server:             {b['size']} in {b['region']} ({b['image']})\n"
            f"Extra SSH keys:     {keys}\n"
            f"Let's Encrypt:      {b['letsencrypt_email']}\n"
            f"Administrator:      {b['admin_username']} <{b['admin_email']}>\n"
            f"Database passwords: {db}\n\n"
            "Deploy queues the run on the service. You can close the progress "
            "window at any time; the run continues and appears under Deploy History."
        )

    # -- loading -------------------------------------------------------------

    def _load_providers(self) -> None:
        self._in_flight.append(
            run_in_thread(
                self._client.list_provider_credentials,
                on_success=self._providers_loaded,
                on_error=self._on_error,
                parent=self,
            )
        )

    def _providers_loaded(self, records: list[dict[str, Any]]) -> None:
        self._providers = {r["provider"]: r for r in records or []}
        for key, label in (("digitalocean", self._do_status), ("cloudflare", self._cf_status)):
            rec = self._providers.get(key)
            if rec and rec.get("configured"):
                label.setText("✓ Configured" + (f" — {rec['label']}" if rec.get("label") else ""))
                label.setStyleSheet("color: #1e8449;")
            else:
                label.setText("Not set")
                label.setStyleSheet("color: #b9770e;")
        if all((self._providers.get(k) or {}).get("configured") for k in ("digitalocean", "cloudflare")):
            self._load_catalogs()

    def _load_catalogs(self) -> None:
        self._in_flight.append(
            run_in_thread(
                self._client.get_digitalocean_options,
                on_success=self.apply_options,
                on_error=self._on_error,
                parent=self,
            )
        )
        self._in_flight.append(
            run_in_thread(
                self._client.list_cloudflare_zones,
                on_success=self.apply_zones,
                on_error=self._on_error,
                parent=self,
            )
        )

    def apply_options(self, options: dict[str, Any]) -> None:
        """Populate the server page from a DigitalOcean catalog payload."""
        self._options = options or {}
        self.region.clear()
        for r in self._options.get("regions", []):
            self.region.addItem(f"{r.get('name')} ({r['slug']})", r["slug"])
        self.image.clear()
        for i in self._options.get("images", []):
            self.image.addItem(i.get("name") or i["slug"], i["slug"])
        self.ssh_keys.clear()
        for k in self._options.get("ssh_keys", []):
            item = QListWidgetItem(f"{k.get('name')} ({k.get('fingerprint')})")
            item.setData(Qt.ItemDataRole.UserRole, k["id"])
            item.setFlags(item.flags() | Qt.ItemFlag.ItemIsUserCheckable)
            item.setCheckState(Qt.CheckState.Unchecked)
            self.ssh_keys.addItem(item)
        self._refresh_sizes()

    def _refresh_sizes(self) -> None:
        region = self.region.currentData()
        self.size.clear()
        for s in self._options.get("sizes", []):
            if region and s.get("regions") and region not in s["regions"]:
                continue
            price = s.get("price_monthly")
            text = f"{s['slug']} — {s.get('vcpus')} vCPU, {s.get('memory')} MB"
            if price is not None:
                text += f", ${price}/mo"
            self.size.addItem(text, s["slug"])

    def apply_zones(self, zones: list[dict[str, Any]]) -> None:
        self._zones = zones or []
        self.zone.clear()
        for z in self._zones:
            self.zone.addItem(z["name"], z["id"])
        self._refresh_fqdn()

    def _refresh_fqdn(self) -> None:
        sub = self.subdomain.text().strip().lower()
        zone = self.zone.currentText()
        self.fqdn.setText(f"{sub}.{zone}" if sub and zone else "—")

    def _toggle_db_fields(self, auto: bool) -> None:
        self.db_password.setVisible(not auto)
        self.db_root_password.setVisible(not auto)

    def _open_credentials(self) -> None:
        dialog = ProviderCredentialsDialog(self._client, parent=self)
        dialog.connection_lost.connect(self.connection_lost)
        try:
            dialog.exec()
        finally:
            dialog.deleteLater()
        self._load_providers()

    def done(self, result: int) -> None:  # noqa: D401 - Qt override
        """Finish the in-flight workers before the dialog is torn down."""
        drain_workers(self._in_flight)
        super().done(result)

    # -- deploy --------------------------------------------------------------

    def _deploy(self) -> None:
        self._next_btn.setEnabled(False)
        body = self.build_body()
        self._in_flight.append(
            run_in_thread(
                lambda: self._client.create_deploy_run(body),
                on_success=self._queued,
                on_error=self._deploy_failed,
                parent=self,
            )
        )

    def _queued(self, run: dict[str, Any]) -> None:
        ident = run.get("deploy_run_identifier") or ""
        self.run_queued.emit(ident)
        self.accept()

    def _deploy_failed(self, exc: Exception) -> None:
        self._next_btn.setEnabled(True)
        if isinstance(exc, RequestShapeError):
            problems = "; ".join(
                f"{e.get('field')}: {e.get('message')}" for e in (exc.errors or [])
            ) or str(exc)
            self._notice.setText(f"Not queued — {problems}")
            return
        self._on_error(exc)

    def _on_error(self, exc: Exception) -> None:
        if isinstance(exc, StorageConnectionError):
            self.connection_lost.emit(str(exc))
        _log.warning("deploy wizard: %s", exc)
        detail = str(getattr(exc, "errors", "")) if isinstance(exc, StorageClientError) else None
        ErrorDialog(
            title="Deploy wizard", message=str(exc), detail=detail or None, parent=self
        ).exec()
